'use client';

import { useCallback, useEffect, useState } from 'react';
import { directionalDisplay } from '../lib/probability';
import type { Dashboard, Options, Sample, Structure } from '../lib/dashboard';

const number = (value?: number | null, digits = 2) => typeof value === 'number' && Number.isFinite(value) ? value.toLocaleString('en-IN', { maximumFractionDigits: digits, minimumFractionDigits: digits }) : '—';
const words = (value?: string) => value ? value.replaceAll('_', ' ') : 'Unavailable';
const time = (value?: string) => value && !Number.isNaN(Date.parse(value)) ? new Date(value).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }) + ' IST' : 'Not recorded';

export default function Home() {
  const [data, setData] = useState<Dashboard | null>(null);
  const [loading, setLoading] = useState(true);
  const [failure, setFailure] = useState(false);
  const [tab, setTab] = useState('Overview');
  const [symbol, setSymbol] = useState<'nifty' | 'banknifty'>('nifty');
  const [filter, setFilter] = useState('All records');
  const [selected, setSelected] = useState<Sample | null>(null);
  const refresh = useCallback(async (signal?: AbortSignal) => {
    setLoading(true);
    try {
      const response = await fetch('/api/dashboard', { cache: 'no-store', signal });
      if (!response.ok) throw new Error('unavailable');
      const next = await response.json();
      if (!next.fetched_at || !next.errors) throw new Error('invalid');
      setData(next); setFailure(false);
    } catch { if (!signal?.aborted) { setData(null); setFailure(true); } }
    finally { if (!signal?.aborted) setLoading(false); }
  }, []);
  useEffect(() => { const controller = new AbortController(); void refresh(controller.signal); return () => controller.abort(); }, [refresh]);
  useEffect(() => { if (loading) return; const timer = setTimeout(() => void refresh(), 30000); return () => clearTimeout(timer); }, [loading, refresh]);
  const setup = data?.duel?.decision;
  const decision = data?.duel?.lifecycle;
  const families = data?.duel?.evidence_families;
  const probability = directionalDisplay(setup?.probability_review);
  const ready = families?.readiness?.live_evidence_ready === true;
  const options = data?.[symbol];
  const samples = Array.isArray(data?.journal?.samples) ? data.journal.samples : [];
  const visible = samples.filter(s => filter === 'All records' || ['DETECTED', 'NO_SETUP'].includes(s.decision?.status || ''));
  const errors = Object.keys(data?.errors || {});
  const reviewBlockers = [...new Set([...(data?.review?.missing_data || []),
    ...(data?.review?.deterministic?.candidates?.flatMap(c => c.missing_data || []) || [])])];

  return <main>
    <header><a className="brand" href="/" aria-label="Dante X home"><span className="brand-lockup"><span className="brand-wordmark" aria-label="Dante X"><span className="brand-dante">Dante</span><span className="brand-x">X</span></span><small>Dx Market Intelligence</small></span></a><div className="header-right"><span className="pill amber">● SHADOW RESEARCH</span><span className="connection">{data?.health ? 'Engine connected' : loading ? 'Connecting…' : 'Engine unavailable'}</span></div></header>
    <div className="toolbar"><nav aria-label="Main navigation">{['Overview', 'Options', 'Signals', 'Journal'].map(name => <button key={name} className={tab === name ? 'active' : ''} onClick={() => setTab(name)} aria-current={tab === name ? 'page' : undefined}>{name}</button>)}</nav><button className="refresh" disabled={loading} onClick={() => void refresh()}>{loading ? 'Refreshing…' : '↻ Refresh'}</button></div>
    <div className="page-heading"><div><div className="eyebrow">THE MARKET, WITH CONTEXT</div><h1>{tab === 'Overview' ? 'Your market command centre.' : tab === 'Options' ? 'Inside the option chain.' : tab === 'Signals' ? 'Follow the paper signal.' : 'Every observation, on record.'}</h1><p>{tab === 'Overview' ? 'Two indices. Independent evidence. One accountable decision.' : tab === 'Options' ? 'Nearest-expiry contracts, with execution and positioning data.' : tab === 'Signals' ? 'Locked plans. Recorded transitions. No broker execution.' : 'Review saved decisions and market snapshots without rewriting history.'}</p></div><div className="update">Last retrieved<><br/><strong>{time(data?.fetched_at)}</strong></></div></div>
    {(failure || errors.length > 0) && <div role="alert" className="notice danger">{failure ? 'Dashboard connection failed. No current values are available.' : `Some sources are unavailable: ${errors.join(', ')}. Missing values are not treated as confirmation.`}</div>}
    <div className="notice"><span className="status-dot"/><span><b>{words(data?.observer?.state)}</b> · {ready ? 'Required evidence passed freshness checks.' : 'Live evidence is not ready for authorization.'} Values may describe the latest completed session.</span></div>
    {(tab === 'Overview' || tab === 'Signals') && <details className="notice"><summary>Four-way review: {words(data?.review?.final?.action)} · {data?.review?.feed_fresh === true ? 'Fresh' : 'Stale or unavailable'}</summary><p>Reviewed at {time(data?.review?.timestamp)}. Independent review does not authorize a trade.</p>{reviewBlockers.length ? <ul>{reviewBlockers.map(reason => <li key={reason}>{words(reason)}</li>)}</ul> : <p>No review blockers reported. Calibration and authorization gates still apply.</p>}</details>}

    {tab === 'Overview' && <>
      <section className="market-grid" aria-label="Index overview"><Market symbol="NIFTY 50" options={data?.nifty} structure={data?.duel?.nifty?.structure}/><Market symbol="BANK NIFTY" options={data?.banknifty} structure={data?.duel?.banknifty?.structure}/></section>
      <div className="content-grid"><section className="panel decision"><div className="section-label">01 / PAPER SIGNAL <span className="pill">{words(decision?.authorization)}</span></div><h2 className="decision-title">{words(decision?.status || data?.duel?.state)}</h2><p>{decision?.reason || (!!decision?.contract ? 'A research setup has been detected. Reference levels below are not execution authorization.' : 'Waiting for a complete engine decision.')}</p><div className="decision-stats"><Metric label="Consensus" value={words(families?.state)}/><Metric label="CE directional probability" value={probability.ce}/><Metric label="PE directional probability" value={probability.pe}/><Metric label="Data quality" value={probability.quality}/></div><p className="muted">Paper simulation · Setup scan: {words(setup?.status)} · Tracking: {words(decision?.tracking_status)}{decision?.previous_status ? ` (last recorded state: ${words(decision.previous_status)})` : ""}. GO is a simulated trigger, not an order or fill.</p><p className="muted">{probability.label} {probability.reasons.join(" · ")}</p><div className="signal-steps">{["WAIT", "GO", "HOLD", "WARNING", "EXIT"].map(s => <span className={decision?.status === s ? "step current" : "step"} key={s}>{s}</span>)}</div>{!!decision?.contract && <><div className="contract">NIFTY {number(decision.contract?.strike, 0)} {decision.direction} · {decision.contract?.expiry}</div><div className="levels">{[['Reference entry', decision.reference_entry], ['Reference stop', decision.reference_stop], ['Target 1', decision.reference_t1], ['Target 2', decision.reference_t2], ['Observed premium', decision.current_premium]].map(([label, value]) => <Metric key={String(label)} label={String(label)} value={'₹' + number(value as number)}/>)}</div></>}{!!families?.readiness?.blocked_sources?.length && <details><summary>Why is authorization blocked?</summary><ul>{families.readiness.blocked_sources.map(s => <li key={s}>{words(s)}</li>)}</ul></details>}</section>
      <section className="panel"><div className="section-label">02 / EVIDENCE FAMILIES <span>{Object.keys(families?.families || {}).length} sources</span></div><div className="evidence-list">{Object.entries(families?.families || {}).map(([name, family]) => <details key={name}><summary><span>{words(name)}</span><span className={'pill ' + (family.state === 'CE' ? 'green' : family.state === 'PE' || family.state === 'CONFLICT' ? 'red' : '')}>{words(family.state)}</span></summary><p>{family.reasons?.join(' · ') || 'No explanation supplied.'}</p></details>)}{!families?.families && <Empty text="Evidence will appear when the engine supplies a complete snapshot."/>}</div></section></div>
      <section className="panel recording"><div><div className="section-label">03 / OBSERVATION RECORDER</div><h3>{data?.observer?.recording_hours || 'Recording schedule unavailable'}</h3><p>After market close, observations are context only.</p></div><Metric label="Last persisted" value={time(data?.observer?.last_persisted_at)}/><button className="secondary" onClick={() => setTab('Journal')}>Open journal ↗</button></section>
    </>}

    {tab === 'Options' && <section className="panel"><div className="panel-toolbar"><div className="switch" aria-label="Choose index">{(['nifty', 'banknifty'] as const).map(s => <button key={s} aria-pressed={symbol === s} className={symbol === s ? 'selected' : ''} onClick={() => setSymbol(s)}>{s === 'nifty' ? 'NIFTY 50' : 'BANK NIFTY'}</button>)}</div><span className="muted">Expiry {options?.expiry || '—'} · Spot {number(options?.spot)} · {words(options?.status)}</span></div><p className="muted">Retrieval time is not exchange freshness. A recent retrieval does not authorize a trade.</p><div className="table-scroll"><table><thead><tr>{['Call LTP', 'Call IV', 'Call OI', 'Call spread %', 'Strike', 'Put LTP', 'Put IV', 'Put OI', 'Put spread %'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{options?.strikes?.map(row => <tr className={row.strike === options.atm_strike ? 'atm' : ''} key={row.strike}><td>{number(row.call.ltp)}</td><td>{number(row.call.iv)}</td><td>{number(row.call.oi, 0)}</td><td>{number(row.call.spread_pct)}</td><th>{number(row.strike, 0)}{row.strike === options.atm_strike && <small> ATM</small>}</th><td>{number(row.put.ltp)}</td><td>{number(row.put.iv)}</td><td>{number(row.put.oi, 0)}</td><td>{number(row.put.spread_pct)}</td></tr>)}</tbody></table></div>{!options?.strikes?.length && <Empty text="No option contracts available for this snapshot."/>}<div className="chain-footer"><Metric label="Neighborhood OI PCR" value={number(options?.positioning?.pcr_oi)}/><Metric label="Call OI wall" value={number(options?.positioning?.call_wall, 0)}/><Metric label="Put OI wall" value={number(options?.positioning?.put_wall, 0)}/></div><p className="muted">{options?.positioning?.scope}</p><div className="chain-footer"><Metric label="Option response" value={words(options?.path_response?.state)}/><Metric label="Baseline samples" value={number(options?.path_response?.samples, 0)}/><Metric label="Last observation" value={time(options?.path_response?.last_sample_at)}/></div></section>}

    {tab === 'Signals' && <section className="panel"><div className="section-label">PERSISTED PAPER LIFECYCLE <span className="pill amber">SHADOW ONLY</span></div><h2>{words(decision?.status)}</h2><p>{decision?.reason || 'Waiting for the engine.'}</p><p className="muted">New entries stop at 15:10 IST; the existing intraday policy closes paper tracking at 15:20. Observations continue through 15:39. Plans use the existing premium reference levels, not an executable structural trade plan. The current selector covers NIFTY options; BANKNIFTY supplies confirming context.</p><div className="decision-stats"><Metric label="CE directional probability" value={probability.ce}/><Metric label="PE directional probability" value={probability.pe}/><Metric label="Data quality" value={probability.quality}/><Metric label="Locked entry" value={number(decision?.reference_entry)}/></div><p className="muted">{probability.label} {probability.reasons.join(" · ")}</p><h3>Signal transitions</h3><div className="table-scroll"><table><thead><tr><th>Time · IST</th><th>State</th><th>Direction</th><th>Reason</th></tr></thead><tbody>{data?.signals?.events?.map((event, i) => <tr key={`${event.signal_id}-${i}`}><td>{time(event.updated_at)}</td><td>{words(event.status)}</td><td>{event.direction || '—'}</td><td className="reason-cell">{event.reason}</td></tr>)}</tbody></table></div>{!data?.signals?.events?.length && <Empty text="No paper signal transitions recorded yet. They will appear when fresh evidence produces a setup."/>}</section>}
    {tab === 'Journal' && <section className="panel"><div className="panel-toolbar"><div><div className="section-label">SAVED OBSERVATIONS</div><p className="muted">Latest {samples.length} records · Historical decisions retain their original logic.</p></div><label className="filter">Show <select value={filter} onChange={e => setFilter(e.target.value)}><option>All records</option><option>Decisions only</option></select></label></div><div className="table-scroll"><table><thead><tr><th>Recorded at · IST</th><th>Decision</th><th>NIFTY</th><th>BANK NIFTY</th><th>Authorization</th><th>Details</th></tr></thead><tbody>{visible.map(s => <tr key={s.id}><td>{time(s.recorded_at)}</td><td>{words(s.decision?.status || s.state)}</td><td>{number(s.market_snapshot?.nifty_spot)}</td><td>{number(s.market_snapshot?.banknifty_spot)}</td><td>{words(s.decision?.authorization)}</td><td><button className="text-button" onClick={() => setSelected(selected?.id === s.id ? null : s)} aria-expanded={selected?.id === s.id}>#{s.id} ↗</button></td></tr>)}</tbody></table></div>{!visible.length && <Empty text="No matching saved records in the latest batch."/>}{selected && <div className="record-detail"><div className="panel-toolbar"><h3>Record #{selected.id}</h3><button className="secondary" onClick={() => setSelected(null)}>Close details</button></div><p>{selected.decision?.reason || 'Observation record; no directional decision reason supplied.'}</p><pre>{JSON.stringify(selected, null, 2)}</pre></div>}</section>}
    <footer><span>DANTE X <b> / </b> Read-only research</span><span>No broker orders · Probability withheld until validated · Refreshes every 30 seconds</span></footer>
  </main>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }
function Market({ symbol, options, structure }: { symbol: string; options?: Options | null; structure?: Structure }) { return <section className="market-card"><div className="section-label">{symbol}<span className="pill">{words(structure?.trend)}</span></div><div className="spot">{number(options?.spot)}</div><p>{words(structure?.opening_range_state)}</p><div className="market-stats"><Metric label="EMA 9" value={number(structure?.ema9)}/><Metric label="EMA 20" value={number(structure?.ema20)}/><Metric label="ATR 14" value={number(structure?.atr14)}/></div><div className="candle-time">Structure candle · {time(structure?.last_candle_ts)}</div></section>; }
